#!/bin/bash
# Generated by Terraform - Vultisig Cluster Setup
set -euo pipefail

export MASTER_IP="${master_ip}"
export MASTER_PRIVATE_IP="${master_private}"
export K3S_TOKEN="${k3s_token}"
%{ for region, ip in workers ~}
export WORKER_${upper(region)}_IP="${ip}"
%{ endfor ~}

%{ if ssh_key_path != "" ~}
export SSH_KEY="${ssh_key_path}"
SSH_OPTS="-i $SSH_KEY -o StrictHostKeyChecking=no"
%{ else ~}
SSH_OPTS="-o StrictHostKeyChecking=no"
%{ endif ~}

echo "Vultisig Cluster Environment"
echo "============================"
echo "Master: $MASTER_IP (private: $MASTER_PRIVATE_IP)"
%{ for region, ip in workers ~}
echo "Worker ${region}: ${ip}"
%{ endfor ~}
echo ""

ssh_master() {
    ssh $SSH_OPTS root@$MASTER_IP "$@"
}

%{ for region, ip in workers ~}
ssh_worker_${region}() {
    ssh $SSH_OPTS root@${ip} "$@"
}
%{ endfor ~}

echo "Functions available: ssh_master, ssh_worker_fsn1, ssh_worker_nbg1, ssh_worker_hel1"
